function [FAAb,dFAAb] = equationFAAb(s,y,in3,in4)
%equationFAAb
%    [FAAb,dFAAb] = equationFAAb(S,Y,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    20-Dec-2023 16:12:39

dfds = in3(:,23);
dfdt0 = in3(:,28);
dfdss = in3(:,24);
dfdyy = in3(:,26);
dpds = in3(:,16);
dpdy = in3(:,18);
duds = in3(:,9);
dudt0 = in3(:,14);
dudy = in3(:,11);
dudss = in3(:,10);
dudys = in3(:,13);
dudyy = in3(:,12);
dwds = in3(:,2);
dwdt0 = in3(:,7);
dwdy = in3(:,4);
dwdss = in3(:,3);
dwdys = in3(:,6);
dwdyy = in3(:,5);
f = in3(:,22);
pa_1 = in4(1,:);
u = in3(:,8);
w = in3(:,1);
t2 = dfds.^2;
t3 = y.^2;
t4 = 1.0./f;
t8 = -w;
t9 = 1.0./y;
t5 = t4.^2;
t6 = t4.^3;
t10 = 1.0./t3;
t12 = dudy.*t4;
t13 = t4.*u;
t14 = dfds.*t4.*y;
t15 = dfdt0.*t4.*y;
t16 = dwdy.*t4.*y;
t7 = t5.^2;
t11 = dfdss.*t5;
t17 = dfdss.*t6.*2.0;
t18 = dfds.*t12.*y;
t19 = dwdy.*t14;
t20 = t14.*w;
t21 = -t13;
t22 = pa_1.*t14.*2.0;
t23 = t2.*t6.*2.0;
t25 = t5.*t9;
t30 = t2.*t3.*t5;
t24 = t2.*t7.*6.0;
t26 = -t19;
t27 = -t22;
t28 = -t23;
t31 = t5+t30;
t29 = -t24;
t32 = t11+t28;
t33 = pa_1.*t31;
t34 = t17+t29;
t35 = f.*t32.*y;
t36 = -t35;
FAAb = [-dpds-dwdt0+t8.*(dwds+t26)+dpdy.*t14+dwdy.*t15+dwdy.*t21+pa_1.*(dwdss+dwdy.*t25+dwdy.*t36+dwdyy.*t5-dwdys.*t14.*2.0+dwdyy.*t30),-dudt0-dpdy.*t4-t12.*u+pa_1.*(dudss+dudy.*t25+dudy.*t36+dudyy.*t5-dudys.*t14.*2.0+dudyy.*t30-t5.*t10.*u)+t8.*(duds-t18)+dfdt0.*t12.*y,dwds+t12+t26+t9.*t13,dfdyy];
if nargout > 1
    t37 = t25+t36;
    t38 = pa_1.*t37;
    t39 = t15+t20+t21+t38;
    mt1 = [-dwds+t19,-duds+t18,0.0,0.0,t8,0.0,1.0,0.0,pa_1,0.0,0.0,0.0,t39,0.0,-t14,0.0,t33,0.0,0.0,0.0,t27,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,-dwdy.*t4,-t12-pa_1.*t5.*t10,t4.*t9,0.0,0.0,t8,0.0,0.0,0.0,pa_1,0.0,0.0,0.0,t39,t4,0.0,0.0,t33,0.0,0.0,0.0,t27,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t14,-t4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-pa_1.*(dwdyy.*t6.*2.0+dwdy.*t6.*t9.*2.0+dwdyy.*t3.*t23+dwdy.*t32.*y-dfds.*dwdys.*t5.*y.*2.0-dwdy.*f.*t34.*y)+dwdy.*t5.*u-dfds.*dpdy.*t5.*y-dfdt0.*dwdy.*t5.*y+dfds.*dwdy.*t5.*t8.*y];
    mt2 = [dpdy.*t5-pa_1.*(dudyy.*t6.*2.0+dudy.*t6.*t9.*2.0+dudyy.*t3.*t23+dudy.*t32.*y-t6.*t10.*u.*2.0-dfds.*dudys.*t5.*y.*2.0-dudy.*f.*t34.*y)+dudy.*t5.*u-dfdt0.*dudy.*t5.*y+dfds.*dudy.*t5.*t8.*y,-dudy.*t5-t25.*u+dfds.*dwdy.*t5.*y,0.0,pa_1.*(dwdys.*t4.*y.*-2.0+dfds.*dwdyy.*t3.*t5.*2.0+dfds.*dwdy.*t5.*y.*4.0)+t16.*w+dpdy.*t4.*y,pa_1.*(dudys.*t4.*y.*-2.0+dfds.*dudyy.*t3.*t5.*2.0+dfds.*dudy.*t5.*y.*4.0)+t12.*w.*y,-t16,0.0,-pa_1.*t16,-pa_1.*t12.*y,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,t16,t12.*y,0.0,0.0];
    dFAAb = reshape([mt1,mt2],4,28);
end
