function [FAAr,dFAAr] = equationFAAr(s,in2,in3)
%equationFAAr
%    [FAAr,dFAAr] = equationFAAr(S,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    27-Nov-2023 13:27:28

g = in2(:,5);
u = in2(:,1);
FAAr = [u+1.0,g-1.0];
if nargout > 1
    dFAAr = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,8]);
end
end
